field.value.poetry_request_id:
  type: mapping
  label: Default value
  mapping:
    code:
      type: string
      label: Code
    year:
      type: string
      label: Year
    number:
      type: integer
      label: Year
    version:
      type: integer
      label: Version
    part:
      type: integer
      label: Part
    product:
      type: string
      label: Product

field.value.oe_translation_poetry_personal_contact:
  type: mapping
  label: Default value
  mapping:
    author:
      type: string
      label: Author
    secretary:
      type: string
      label: Secretary
    contact:
      type: string
      label: Contact
    responsible:
      type: string
      label: Responsible

field.value.oe_translation_poetry_organisation_contact:
  type: mapping
  label: Default value
  mapping:
    responsible:
      type: string
      label: Responsible
    author:
      type: string
      label: Author
    requester:
      type: string
      label: Requester

tmgmt.translator.settings.poetry:
  type: mapping
  mapping:
    identifier_code:
      type: string
      label: Identifier code
    title_prefix:
      type: string
      label: Request title prefix
    site_id:
      type: string
      label: The ID of the site
    application_reference:
      type: string
      label: Application reference code
    contact:
      type: mapping
      label: Contact information
      mapping:
        auteur:
          type: string
          label: Author
        secretaire:
          type: string
          label: Secretary
        contact:
          type: string
          label: Contact
        responsable:
          type: string
          label: Responsible
    organisation:
      type: mapping
      label: Organisation information
      mapping:
        responsible:
          type: string
          label: Responsible
        author:
          type: string
          label: Author
        requester:
          type: string
          label: Requester
